/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;



import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.LoanRequest;
import model.User;
import util.DatabaseConnector;

/**
 *
 * @author Farid
 */
public class LoginFram extends javax.swing.JFrame {

// logIn => check for empty input. //
// Admin LogIn and Admin Dashboard. //
        
    
    User loggedInUser;
    List<Book> searchBooks;
    /**
     * Creates new form LoginFram
     */
    
    public LoginFram() {
        initComponents();
        jPanel1.setVisible(false);
        dashboardPanel.setVisible(false);
        addBookPanel.setVisible(false);
        browseBookPanel.setVisible(false);
        lendRequestPanel.setVisible(false);
        borrowedBookPanel.setVisible(false);
        adminDashboardPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        logInPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTextField1 = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        passwordTextField1 = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        registerButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        dashboardPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logoutButtonDashboard = new javax.swing.JButton();
        myLendRequestButtonDashboard = new javax.swing.JButton();
        borrowedBookButtonDashboard = new javax.swing.JButton();
        addBookButtonDashboard = new javax.swing.JButton();
        browseBookButtonDashboard = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailTextFieldDashboard = new javax.swing.JTextField();
        passwordTextFieldDashboard = new javax.swing.JTextField();
        editButtonDashboard = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userBookTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        removeBookButtonDashboard = new javax.swing.JButton();
        usernameTextFieldDashboard = new javax.swing.JLabel();
        addBookPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        titleTextFieldAddBook = new javax.swing.JTextField();
        authorTextFieldAddBook = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextAreaAddBook = new javax.swing.JTextArea();
        backButtonAddBook = new javax.swing.JButton();
        addButtonAddBook = new javax.swing.JButton();
        browseBookPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        titleRadioButton = new javax.swing.JRadioButton();
        authorRadioButton = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        loanRequestButton = new javax.swing.JButton();
        browseBookBackButton = new javax.swing.JButton();
        borrowedBookPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        borrowedBookTable = new javax.swing.JTable();
        returnBookButton = new javax.swing.JButton();
        borrowedBookBackButton = new javax.swing.JButton();
        lendRequestPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        acceptButton = new javax.swing.JButton();
        lendRequestBackButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        adminDashboardPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        logoutAdminButton = new javax.swing.JButton();
        removeUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 620));

        logInPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("BookShare Hub");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Login");

        usernameLabel.setText("UserName: ");

        passwordLabel.setText("Password: ");

        loginButton.setBackground(new java.awt.Color(204, 204, 204));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(204, 204, 204));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logInPanelLayout = new javax.swing.GroupLayout(logInPanel);
        logInPanel.setLayout(logInPanelLayout);
        logInPanelLayout.setHorizontalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logInPanelLayout.createSequentialGroup()
                .addGap(0, 845, Short.MAX_VALUE)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel))
                        .addGap(108, 108, 108)
                        .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTextField)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                    .addGroup(logInPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(278, 278, 278))
        );
        logInPanelLayout.setVerticalGroup(
            logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(52, 52, 52)
                .addGroup(logInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(850, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("BookShare Hub");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("Register");

        usernameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField1ActionPerformed(evt);
            }
        });

        usernameLabel1.setText("UserName: ");

        emailLabel.setText("Email: ");

        passwordLabel1.setText("Password: ");

        registerButton1.setBackground(new java.awt.Color(204, 204, 204));
        registerButton1.setText("Register");
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 281, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel1)
                            .addComponent(emailLabel)
                            .addComponent(passwordLabel1))
                        .addGap(159, 159, 159)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameTextField1)
                            .addComponent(emailTextField)
                            .addComponent(passwordTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addGap(267, 267, 267))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(331, 331, 331))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel1))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        dashboardPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setText("BookShare Hub");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("Dashboard");

        logoutButtonDashboard.setText("Logout");
        logoutButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonDashboardActionPerformed(evt);
            }
        });

        myLendRequestButtonDashboard.setText("My Lend Request");
        myLendRequestButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myLendRequestButtonDashboardActionPerformed(evt);
            }
        });

        borrowedBookButtonDashboard.setText("Borrowed Book");
        borrowedBookButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowedBookButtonDashboardActionPerformed(evt);
            }
        });

        addBookButtonDashboard.setText("Add Book");
        addBookButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonDashboardActionPerformed(evt);
            }
        });

        browseBookButtonDashboard.setText("Browse Book");
        browseBookButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBookButtonDashboardActionPerformed(evt);
            }
        });

        jLabel7.setText("UserName: ");

        jLabel8.setText("Email: ");

        jLabel9.setText("Password: ");

        editButtonDashboard.setText("Edit");
        editButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonDashboardActionPerformed(evt);
            }
        });

        userBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Title", "Author", "Availability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userBookTable);
        if (userBookTable.getColumnModel().getColumnCount() > 0) {
            userBookTable.getColumnModel().getColumn(0).setResizable(false);
            userBookTable.getColumnModel().getColumn(1).setResizable(false);
            userBookTable.getColumnModel().getColumn(2).setResizable(false);
            userBookTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel10.setText("List of your books:");

        removeBookButtonDashboard.setText("Remove Book");
        removeBookButtonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookButtonDashboardActionPerformed(evt);
            }
        });

        usernameTextFieldDashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                                        .addComponent(addBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(removeBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                        .addComponent(browseBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(borrowedBookButtonDashboard)
                                        .addGap(18, 18, 18)
                                        .addComponent(myLendRequestButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(logoutButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editButtonDashboard)
                    .addGroup(dashboardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(usernameTextFieldDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(emailTextFieldDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(passwordTextFieldDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameTextFieldDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(emailTextFieldDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(passwordTextFieldDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(editButtonDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowedBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myLendRequestButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBookButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        addBookPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel11.setText("BookShare Hub");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel12.setText("Add Book");

        jLabel13.setText("Title: ");

        jLabel14.setText("Author: ");

        jLabel15.setText("Description: ");

        descriptionTextAreaAddBook.setColumns(20);
        descriptionTextAreaAddBook.setRows(5);
        jScrollPane2.setViewportView(descriptionTextAreaAddBook);

        backButtonAddBook.setText("Back");
        backButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonAddBookActionPerformed(evt);
            }
        });

        addButtonAddBook.setText("Add");
        addButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonAddBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addBookPanelLayout = new javax.swing.GroupLayout(addBookPanel);
        addBookPanel.setLayout(addBookPanelLayout);
        addBookPanelLayout.setHorizontalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(backButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(addButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addBookPanelLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addBookPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(55, 55, 55)
                                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addBookPanelLayout.createSequentialGroup()
                                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(78, 78, 78)
                                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(authorTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(titleTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        addBookPanelLayout.setVerticalGroup(
            addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBookPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(51, 51, 51)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(titleTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(authorTextFieldAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        browseBookPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel16.setText("BookShare Hub");

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel17.setText("Browse Book");

        jLabel18.setText("Search By: ");

        buttonGroup.add(titleRadioButton);
        titleRadioButton.setSelected(true);
        titleRadioButton.setText("Title");
        titleRadioButton.setActionCommand("1");
        titleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup.add(authorRadioButton);
        authorRadioButton.setText("Author");
        authorRadioButton.setActionCommand("2");

        jLabel19.setText("Input: ");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bookID", "Title", "Author", "Avalability"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(searchTable);
        if (searchTable.getColumnModel().getColumnCount() > 0) {
            searchTable.getColumnModel().getColumn(0).setResizable(false);
            searchTable.getColumnModel().getColumn(1).setResizable(false);
            searchTable.getColumnModel().getColumn(2).setResizable(false);
            searchTable.getColumnModel().getColumn(3).setResizable(false);
        }

        loanRequestButton.setText("Loan Request");
        loanRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanRequestButtonActionPerformed(evt);
            }
        });

        browseBookBackButton.setText("Back");
        browseBookBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBookBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout browseBookPanelLayout = new javax.swing.GroupLayout(browseBookPanel);
        browseBookPanel.setLayout(browseBookPanelLayout);
        browseBookPanelLayout.setHorizontalGroup(
            browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseBookPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(browseBookPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26)
                        .addGroup(browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(authorRadioButton)
                            .addGroup(browseBookPanelLayout.createSequentialGroup()
                                .addComponent(titleRadioButton)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(82, 82, 82))
            .addGroup(browseBookPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browseBookPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(browseBookBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loanRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        browseBookPanelLayout.setVerticalGroup(
            browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseBookPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(23, 23, 23)
                .addGroup(browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(titleRadioButton)
                    .addComponent(jLabel19)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(browseBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseBookBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        borrowedBookPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel20.setText("BookShare Hub");

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel21.setText("Borrowed Book");

        borrowedBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bookID", "Title", "Author", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(borrowedBookTable);
        if (borrowedBookTable.getColumnModel().getColumnCount() > 0) {
            borrowedBookTable.getColumnModel().getColumn(0).setResizable(false);
            borrowedBookTable.getColumnModel().getColumn(1).setResizable(false);
            borrowedBookTable.getColumnModel().getColumn(2).setResizable(false);
            borrowedBookTable.getColumnModel().getColumn(3).setResizable(false);
        }

        returnBookButton.setText("Return Book");
        returnBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookButtonActionPerformed(evt);
            }
        });

        borrowedBookBackButton.setText("Back");
        borrowedBookBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowedBookBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borrowedBookPanelLayout = new javax.swing.GroupLayout(borrowedBookPanel);
        borrowedBookPanel.setLayout(borrowedBookPanelLayout);
        borrowedBookPanelLayout.setHorizontalGroup(
            borrowedBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowedBookPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(80, 80, 80))
            .addGroup(borrowedBookPanelLayout.createSequentialGroup()
                .addGroup(borrowedBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, borrowedBookPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borrowedBookPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(borrowedBookBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        borrowedBookPanelLayout.setVerticalGroup(
            borrowedBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowedBookPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(borrowedBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(borrowedBookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowedBookBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        lendRequestPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel22.setText("BookShare Hub");

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel23.setText("My Request");

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "requestID", "Title", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(requestTable);
        if (requestTable.getColumnModel().getColumnCount() > 0) {
            requestTable.getColumnModel().getColumn(0).setResizable(false);
            requestTable.getColumnModel().getColumn(1).setResizable(false);
            requestTable.getColumnModel().getColumn(2).setResizable(false);
        }

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        lendRequestBackButton.setText("Back");
        lendRequestBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendRequestBackButtonActionPerformed(evt);
            }
        });

        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lendRequestPanelLayout = new javax.swing.GroupLayout(lendRequestPanel);
        lendRequestPanel.setLayout(lendRequestPanelLayout);
        lendRequestPanelLayout.setHorizontalGroup(
            lendRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lendRequestPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lendRequestPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lendRequestBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(lendRequestPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        lendRequestPanelLayout.setVerticalGroup(
            lendRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lendRequestPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(lendRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(lendRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lendRequestBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        adminDashboardPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel24.setText("BookShare Hub");

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel25.setText("Admin Dashboard");

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel26.setText("Users: ");

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "userId", "Username", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(usersTable);
        if (usersTable.getColumnModel().getColumnCount() > 0) {
            usersTable.getColumnModel().getColumn(0).setResizable(false);
            usersTable.getColumnModel().getColumn(1).setResizable(false);
            usersTable.getColumnModel().getColumn(2).setResizable(false);
        }

        logoutAdminButton.setText("Log out");
        logoutAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAdminButtonActionPerformed(evt);
            }
        });

        removeUserButton.setText("Remove");
        removeUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminDashboardPanelLayout = new javax.swing.GroupLayout(adminDashboardPanel);
        adminDashboardPanel.setLayout(adminDashboardPanelLayout);
        adminDashboardPanelLayout.setHorizontalGroup(
            adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(71, 71, 71))
            .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashboardPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(removeUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        adminDashboardPanelLayout.setVerticalGroup(
            adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashboardPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(41, 41, 41)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(adminDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(addBookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(browseBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(borrowedBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lendRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adminDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logInPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(addBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 634, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(browseBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(borrowedBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lendRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adminDashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        logInPanel.setVisible(false);
        jPanel1.setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void usernameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        logInPanel.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if (isValid_input_register() == 0){
                User newUser = new User(0, usernameTextField1.getText(), emailTextField.getText(), passwordTextField1.getText());
                DatabaseConnector.addUser(newUser);
                JOptionPane.showMessageDialog(null, "User Created Successfully", "Create User", HEIGHT);
                cleanUpRegister();
                jPanel1.setVisible(false);
                logInPanel.setVisible(true);
            }
            else if(isValid_input_register() == 1){
                JOptionPane.showMessageDialog(null, "This username already exist! Please try another username.", "Create User", HEIGHT);
            }
            else if(isValid_input_register() == 2){
                JOptionPane.showMessageDialog(null, "Please input all section correctly!", "Create User", HEIGHT);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_registerButton1ActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String username = usernameTextField.getText();
        String password = passwordTextField.getText();
        List<User> userList = DatabaseConnector.getAllUsers();
        if (username.equals("admin") && password.equals("admin")) {
            logInPanel.setVisible(false);
            adminDashboardLoad();
            adminDashboardPanel.setVisible(true);
        }
        else{
            boolean flag = false;
            for (User user : userList) {
                if (user.getUsername().equals(username) && user.getPassword().equals(password)) {
                    loggedInUser = user;
                    logInPanel.setVisible(false);
                    //System.out.println(loggedInUser.getUserId());
                    dashboardLoad();
                    dashboardPanel.setVisible(true);
                    flag = true;
                }
            }
            if(flag == false)
                JOptionPane.showMessageDialog(null, "Wrong username or password!!", "Log In", HEIGHT);
        }        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void addBookButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButtonDashboardActionPerformed
        // TODO add your handling code here:
        dashboardPanel.setVisible(false);
        addBookPanel.setVisible(true);
    }//GEN-LAST:event_addBookButtonDashboardActionPerformed

    private void borrowedBookButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowedBookButtonDashboardActionPerformed
        // TODO add your handling code here:
        dashboardPanel.setVisible(false);
        borrowedBookLoad();
        borrowedBookPanel.setVisible(true);
    }//GEN-LAST:event_borrowedBookButtonDashboardActionPerformed

    private void titleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleRadioButtonActionPerformed

    private void removeBookButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookButtonDashboardActionPerformed
        // TODO add your handling code here:
        int selectedIndex = userBookTable.getSelectedRow();
        if(selectedIndex == -1){
            JOptionPane.showMessageDialog(null, "Please select a book to remove", "Remove", HEIGHT);            
            return;
        }
        try{
            List<Book> userBooks = DatabaseConnector.getUserOwnedBooks(loggedInUser.getUserId());
            Book selectedBook = userBooks.get(selectedIndex);
            DatabaseConnector.removeBook(selectedBook);
            JOptionPane.showMessageDialog(null, "Book Deleted Successfully", "Remove", HEIGHT);
            dashboardLoad();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
    }//GEN-LAST:event_removeBookButtonDashboardActionPerformed

    private void logoutButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonDashboardActionPerformed
        // TODO add your handling code here:
        dashboardPanel.setVisible(false);
        loggedInUser = null;
        logInPanel.setVisible(true);
        usernameTextField.setText("");
        passwordTextField.setText("");
    }//GEN-LAST:event_logoutButtonDashboardActionPerformed

    private void browseBookButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBookButtonDashboardActionPerformed
        // TODO add your handling code here:
        dashboardPanel.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) searchTable.getModel();
        model.setRowCount(0);
        searchTextField.setText("");
        browseBookPanel.setVisible(true);
    }//GEN-LAST:event_browseBookButtonDashboardActionPerformed

    private void browseBookBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBookBackButtonActionPerformed
        // TODO add your handling code here:
        browseBookPanel.setVisible(false);
        dashboardLoad();
        dashboardPanel.setVisible(true);
    }//GEN-LAST:event_browseBookBackButtonActionPerformed

    private void borrowedBookBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowedBookBackButtonActionPerformed
        // TODO add your handling code here:
        borrowedBookPanel.setVisible(false);
        dashboardLoad();
        dashboardPanel.setVisible(true);
    }//GEN-LAST:event_borrowedBookBackButtonActionPerformed

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        try{
            List<LoanRequest> loanRequests = DatabaseConnector.recieveAllLoanRequestFromOtherUser(loggedInUser);
            int selectedIndex = requestTable.getSelectedRow();
            LoanRequest loanRequest = loanRequests.get(selectedIndex);
            DatabaseConnector.changeLoanRequestStatus(loanRequest, "Denied");
            requestTableLoad();
            JOptionPane.showMessageDialog(null, "The Request Rejected!", "Loan Request", HEIGHT);
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
        
        
        
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void myLendRequestButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myLendRequestButtonDashboardActionPerformed
        // TODO add your handling code here:
        dashboardPanel.setVisible(false);
        requestTableLoad();
        lendRequestPanel.setVisible(true);
    }//GEN-LAST:event_myLendRequestButtonDashboardActionPerformed

    private void lendRequestBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendRequestBackButtonActionPerformed
        // TODO add your handling code here:
        lendRequestPanel.setVisible(false);
        dashboardLoad();
        dashboardPanel.setVisible(true);
    }//GEN-LAST:event_lendRequestBackButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        
        // SEARCH
        String searchBy = buttonGroup.getSelection().getActionCommand();
        System.out.println(searchBy);
        if (searchBy == "1"){
            try{
                searchBooks = DatabaseConnector.browseBookByTitle(searchTextField.getText());
                DefaultTableModel model = (DefaultTableModel) searchTable.getModel();
                model.setRowCount(0);
                for(Book book : searchBooks){
                    if (book.isAvailability()){
                        Object[] row = new Object[4];
                        row[0] = book.getBookId();
                        row[1] = book.getTitle();
                        row[2] = book.getAuthor();
                        row[3] = book.isAvailability();
                        model.addRow(row);
                    }
                }
            } catch( Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());            
            }
        }
        else if(searchBy == "2"){
            try{
                searchBooks = DatabaseConnector.browseBookByAuthor(searchTextField.getText());
                DefaultTableModel model = (DefaultTableModel) searchTable.getModel();
                model.setRowCount(0);
                for(Book book : searchBooks){
                    Object[] row = new Object[4];
                    row[0] = book.getBookId();
                    row[1] = book.getTitle();
                    row[2] = book.getAuthor();
                    row[3] = book.isAvailability();
                    model.addRow(row);
                }
            } catch( Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());            
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Chose one field Title or Author", "Search", HEIGHT);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void loanRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanRequestButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = searchTable.getSelectedRow();
        Book selectedBook = searchBooks.get(selectedIndex);
        int bookRequestedId = selectedBook.getBookId();
        User lenderUser = DatabaseConnector.getUserByBook(selectedBook.getBookId());
        LoanRequest loanRequest = new LoanRequest(0, loggedInUser.getUserId(),lenderUser.getUserId() ,bookRequestedId, "Pending");
        try{
            DatabaseConnector.addLoanRequest(loanRequest);
            JOptionPane.showMessageDialog(null, "Your request create succesfully and sent to lender!", "Loan Request", HEIGHT);
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    }//GEN-LAST:event_loanRequestButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        try{
            List<LoanRequest> loanRequests = DatabaseConnector.recieveAllLoanRequestFromOtherUser(loggedInUser);
            int selectedIndex = requestTable.getSelectedRow();
            LoanRequest loanRequest = loanRequests.get(selectedIndex);
            DatabaseConnector.changeLoanRequestStatus(loanRequest, "Approved");
            //change Avalability:
            int bookId = loanRequest.getBookRequestedId();
            Book book = DatabaseConnector.getBookById(bookId);
            DatabaseConnector.changeBookAvailability(book, false);
            requestTableLoad();
            JOptionPane.showMessageDialog(null, "The Request Approved! Now the book is unavailable.", "Loan Request", HEIGHT);
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
        
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void returnBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookButtonActionPerformed
        // TODO add your handling code here:
        try{
            List<LoanRequest> loanRequests = DatabaseConnector.getAllLoanRequestsByUser(loggedInUser);
            int selectedIndex = borrowedBookTable.getSelectedRow();
            LoanRequest loanRequest = loanRequests.get(selectedIndex);
            DatabaseConnector.changeLoanRequestStatus(loanRequest, "Denied");
            borrowedBookLoad();
            //change Avalability:
            int bookId = loanRequest.getBookRequestedId();
            Book book = DatabaseConnector.getBookById(bookId);
            DatabaseConnector.changeBookAvailability(book, true);
            requestTableLoad();
            JOptionPane.showMessageDialog(null, "Book returned!! Now it's available.", "Return", HEIGHT);
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    }//GEN-LAST:event_returnBookButtonActionPerformed

    private void editButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonDashboardActionPerformed
        // TODO add your handling code here:
        String newEmail = emailTextFieldDashboard.getText();
        String newPassword = passwordTextFieldDashboard.getText();
        if (isValid_input_edit() == 0){
            User newUser = new User(0, loggedInUser.getUsername(), newEmail, newPassword);
            try{
                DatabaseConnector.updateUser(loggedInUser, newUser);
                JOptionPane.showMessageDialog(null, "User Profile Update Successfuly!", "Update User", HEIGHT);
            }catch( Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());            
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please input all section correctly!", "Update User", HEIGHT);
        }
        dashboardLoad();
    }//GEN-LAST:event_editButtonDashboardActionPerformed

    private void logoutAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAdminButtonActionPerformed
        // TODO add your handling code here:
        adminDashboardPanel.setVisible(false);
        loggedInUser = null;
        logInPanel.setVisible(true);
        usernameTextField.setText("");
        passwordTextField.setText("");
    }//GEN-LAST:event_logoutAdminButtonActionPerformed

    private void removeUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserButtonActionPerformed
        // TODO add your handling code here:
        try{
            List<User> userList = DatabaseConnector.getAllUsers();
            int selectedIndex = usersTable.getSelectedRow();
            User user = userList.get(selectedIndex);
            DatabaseConnector.removeUser(user);
            adminDashboardLoad();
            JOptionPane.showMessageDialog(null, "The user remove successfuly!.", "Remove User", HEIGHT);
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    }//GEN-LAST:event_removeUserButtonActionPerformed

    private void addButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonAddBookActionPerformed
        // TODO add your handling code here:
        try{
            if (isValid_input_addBook() == 0){
                Book newBook = new Book(0, titleTextFieldAddBook.getText(), authorTextFieldAddBook.getText(), descriptionTextAreaAddBook.getText(), true);
                DatabaseConnector.addUserOwnedBook(loggedInUser, newBook);
                JOptionPane.showMessageDialog(null, "Book Added Successfully", "Add Book", HEIGHT);
                addBookPanel.setVisible(false);
                titleTextFieldAddBook.setText("");
                authorTextFieldAddBook.setText("");
                descriptionTextAreaAddBook.setText("");
                dashboardLoad();
                dashboardPanel.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Please input all section correctly!", "Add Book", HEIGHT);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_addButtonAddBookActionPerformed

    private void backButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonAddBookActionPerformed
        // TODO add your handling code here:
        addBookPanel.setVisible(false);
        dashboardLoad();
        dashboardPanel.setVisible(true);
    }//GEN-LAST:event_backButtonAddBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFram().setVisible(true);
            }
        });
    }
    
    public void cleanUpRegister(){
        usernameTextField1.setText("");
        emailTextField.setText("");
        passwordTextField1.setText("");
    }
    
    public int isValid_input_edit(){
        if(emailTextFieldDashboard.getText().equals("") || passwordTextFieldDashboard.getText().equals("")){
            return 1;
        }
        else{
            return 0;
        }
    }
    
    public int isValid_input_addBook(){
        if(titleTextFieldAddBook.getText().equals("") || authorTextFieldAddBook.getText().equals("") || descriptionTextAreaAddBook.getText().equals("")){
            return 1;
        }
        else
            return 0;
    }
    
    public int isValid_input_register(){ //login if username exist '1' else if empty '2' ... else '0'
        String username = usernameTextField1.getText();
        List<User> userList = DatabaseConnector.getAllUsers();
        boolean userExist = false;
        for (User user : userList) {
            if (user.getUsername().equals(username)) {
                userExist = true;
            }
        }
        if(userExist){
           return 1; 
        }
        else if(usernameTextField1.getText().equals("") || emailTextField.getText().equals("") || passwordTextField1.getText().equals("")){
           return 2;
        }
        else
           return 0;
    }
    
    public void adminDashboardLoad(){
        try{
            List<User> userList = DatabaseConnector.getAllUsers();
            DefaultTableModel model = (DefaultTableModel) usersTable.getModel();
            model.setRowCount(0);
            for(User user : userList){
                Object[] row = new Object[3];
                row[0] = user.getUserId();
                row[1] = user.getUsername();
                row[2] = user.getEmail();
                model.addRow(row);
            }
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }

    }
    
    public void dashboardLoad(){
        usernameTextFieldDashboard.setText(loggedInUser.getUsername());
        emailTextFieldDashboard.setText(loggedInUser.getEmail());
        passwordTextFieldDashboard.setText(loggedInUser.getPassword());
        
        try{
            List<Book> userBooks = DatabaseConnector.getUserOwnedBooks(loggedInUser.getUserId());
            DefaultTableModel model = (DefaultTableModel) userBookTable.getModel();
            model.setRowCount(0);
            for(Book book : userBooks){
                Object[] row = new Object[4];
                row[0] = book.getBookId();
                row[1] = book.getTitle();
                row[2] = book.getAuthor();
                row[3] = book.isAvailability();
                model.addRow(row);
            }
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    }
    
    public void requestTableLoad(){
        try{
            List<LoanRequest> loanRequests = DatabaseConnector.recieveAllLoanRequestFromOtherUser(loggedInUser);
            DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
            model.setRowCount(0);
            for(LoanRequest loanRequest : loanRequests){
                Object[] row = new Object[4];
                int bookId = loanRequest.getBookRequestedId();
                Book book = DatabaseConnector.getBookById(bookId);
                row[0] = loanRequest.getBookRequestedId();
                row[1] = book.getTitle();
                row[2] = loanRequest.getRequestStatus();
                model.addRow(row);
            }
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    }
    
    public void borrowedBookLoad(){
        try{
            List<LoanRequest> loanRequests = DatabaseConnector.getAllLoanRequestsByUser(loggedInUser);
            DefaultTableModel model = (DefaultTableModel) borrowedBookTable.getModel();
            model.setRowCount(0);
            for(LoanRequest loanRequest : loanRequests){
                Object[] row = new Object[4];
                int bookId = loanRequest.getBookRequestedId();
                Book book = DatabaseConnector.getBookById(bookId);
                row[0] = book.getBookId();
                row[1] = book.getTitle();
                row[2] = book.getAuthor();
                row[3] = loanRequest.getRequestStatus();
                model.addRow(row);
            }
        } catch( Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());            
        }
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton addBookButtonDashboard;
    private javax.swing.JPanel addBookPanel;
    private javax.swing.JButton addButtonAddBook;
    private javax.swing.JPanel adminDashboardPanel;
    private javax.swing.JRadioButton authorRadioButton;
    private javax.swing.JTextField authorTextFieldAddBook;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButtonAddBook;
    private javax.swing.JButton borrowedBookBackButton;
    private javax.swing.JButton borrowedBookButtonDashboard;
    private javax.swing.JPanel borrowedBookPanel;
    private javax.swing.JTable borrowedBookTable;
    private javax.swing.JButton browseBookBackButton;
    private javax.swing.JButton browseBookButtonDashboard;
    private javax.swing.JPanel browseBookPanel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JTextArea descriptionTextAreaAddBook;
    private javax.swing.JButton editButtonDashboard;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emailTextFieldDashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton lendRequestBackButton;
    private javax.swing.JPanel lendRequestPanel;
    private javax.swing.JButton loanRequestButton;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton logoutAdminButton;
    private javax.swing.JButton logoutButtonDashboard;
    private javax.swing.JButton myLendRequestButtonDashboard;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField passwordTextField1;
    private javax.swing.JTextField passwordTextFieldDashboard;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerButton1;
    private javax.swing.JButton rejectButton;
    private javax.swing.JButton removeBookButtonDashboard;
    private javax.swing.JButton removeUserButton;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton returnBookButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable searchTable;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JRadioButton titleRadioButton;
    private javax.swing.JTextField titleTextFieldAddBook;
    private javax.swing.JTable userBookTable;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JTextField usernameTextField;
    private javax.swing.JTextField usernameTextField1;
    private javax.swing.JLabel usernameTextFieldDashboard;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables

    /*
    
    public int isValid(){
        return 0;
    }
    */
}

